# Generated by Django 5.2.7 on 2025-10-04 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('auth', models.CharField(max_length=100, verbose_name='Автор')),
                ('isbn', models.CharField(help_text="13 символов <a href=https://www.isbn-international.org/content/what-isbn'>ISBN номер</a>", max_length=13, verbose_name='isbn')),
                ('genre', models.CharField(choices=[('fiction', 'Художественная литература'), ('science', 'Научная литература'), ('fantasy', 'Фэнтези'), ('detective', 'Детектив'), ('biography', 'Биография')], default='fiction', max_length=50, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, help_text='Краткое описание книги', verbose_name='Описание')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата поступления')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для выдачи')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Количество строниц')),
            ],
        ),
    ]
