# Generated by Django 5.2.7 on 2025-10-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auth',
            new_name='author',
        ),
    ]
